import {
  mdiHome,
  mdiDownload,
  mdiHelp,
  mdiAccount,
  mdiMagnify,
  mdiMenu,
  mdiPlay,
  mdiPause,
  mdiStop,
  mdiShare,
  mdiCart,
  mdiCheck,
  mdiClose,
  mdiFilter,
  mdiCalendar,
  mdiSoccer,
  mdiBasketball,
  mdiVolleyball,
  mdiCreditCard,
  mdiCloudDownload,
  mdiRefresh,
  mdiAlert,
  mdiInformation,
  mdiThemeLightDark,
  mdiChevronDown,
  mdiGoogle
} from '@mdi/js'

export const customIcons = {
  home: mdiHome,
  download: mdiDownload,
  help: mdiHelp,
  account: mdiAccount,
  magnify: mdiMagnify,
  menu: mdiMenu,
  play: mdiPlay,
  pause: mdiPause,
  stop: mdiStop,
  share: mdiShare,
  cart: mdiCart,
  check: mdiCheck,
  close: mdiClose,
  filter: mdiFilter,
  calendar: mdiCalendar,
  soccer: mdiSoccer,
  basketball: mdiBasketball,
  volleyball: mdiVolleyball,
  creditCard: mdiCreditCard,
  cloudDownload: mdiCloudDownload,
  refresh: mdiRefresh,
  alert: mdiAlert,
  information: mdiInformation,
  themeLightDark: mdiThemeLightDark,
  chevronDown: mdiChevronDown,
  google: mdiGoogle
}